05 - Create NotificationMessage component
js-tasks-ru/js-20221021_vovijan pull request #8
Opened 2022-11-07 17:14 UTC by vovijan

2022-11-07 17:14 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-11-08 13:37 UTC, dosandk commented on 05-dom-document-loading/1-notification/index.js
> +    this.text = text || 'hi';
что такое `hi`?

2022-11-08 13:37 UTC, dosandk commented on 05-dom-document-loading/1-notification/index.js
> +    this.duration = duration || 1000;
может значения по умолчанию описать сразу в аргументах?

2022-11-08 13:37 UTC, dosandk commented on 05-dom-document-loading/1-notification/index.js
> +    if (this.type === 'error') {
это можно сделать прямо в шаблоне

2022-11-08 13:38 UTC, dosandk commented on 05-dom-document-loading/1-notification/index.js
>  export default class NotificationMessage {
А где удаление предыдущего нотификейшена?

2022-11-08 13:38 UTC, dosandk requested changes
нотификейшен следует поправить

2022-11-08 13:39 UTC, vovijan commented on 05-dom-document-loading/1-notification/index.js
> +    this.text = text || 'hi';
В тестах присутствует
![image](https://user-images.githubusercontent.com/31822850/200579598-2fa49452-ee07-4e28-a3a7-df9c07d1d4eb.png)

2022-11-08 13:40 UTC, vovijan commented on 05-dom-document-loading/1-notification/index.js
> +    this.duration = duration || 1000;
В каких аргументах? Где?

2022-11-08 13:40 UTC, vovijan commented on 05-dom-document-loading/1-notification/index.js
> +    if (this.type === 'error') {
Где находится шаблон?

2022-11-08 13:41 UTC, vovijan commented on 05-dom-document-loading/1-notification/index.js
>  export default class NotificationMessage {
Его, видимо, нет. Каким образом это реализовать?

2022-11-08 14:15 UTC, vovijan commented on 05-dom-document-loading/1-notification/index.js
>  export default class NotificationMessage {
И какой предыдущий нотификейшен?

2022-11-08 14:17 UTC, vovijan commented on 05-dom-document-loading/1-notification/index.js
> +    if (this.type === 'error') {
И каким образом?

2022-11-08 14:23 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-11-08 15:56 UTC, dosandk commented on 05-dom-document-loading/1-notification/index.js
> +    this.duration = duration || 1000;
```js
constructor(text = '', { duration = 1000, type = '' } = {}) {
```
вот так, помните мы разбирали такой подход с ColumnChart

2022-11-08 16:32 UTC, dosandk commented on 05-dom-document-loading/1-notification/index.js
> +    if (this.type === 'error') {
ну вот же шаблон, 
```
getTemplate() {
    return `
      <div class="notification success" style="--value:${this.duration / 1000}s">
        <div class="timer"></div>
        <div class="inner-wrapper">
          <div class="notification-header">${this.type}</div>
          <div class="notification-body">
            ${this.text}
          </div>
        </div>
      </div>
    `;
  }
```
даже метод называется `get` - дай, `template` - шаблон

2022-11-08 16:33 UTC, dosandk commented on 05-dom-document-loading/1-notification/index.js
> +    if (this.type === 'error') {
с помощью тернарника сделать следует

2022-11-09 21:45 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2022-11-11 16:19 UTC, dosandk commented on 05-dom-document-loading/1-notification/index.js
> +      NotificationMessage.allInstances.forEach(instances => instances.remove());
а зачем массив?
достаточно просто ссылки на предыдущий нотификейшен

2022-11-11 16:19 UTC, dosandk approved these changes
👍 good

2022-11-11 16:20 UTC, merged